const { Graph } = require("./Graph")

const graph = new Graph()
graph.addNode("A")
graph.addNode("B")
graph.addNode("C")
graph.addEdge("A", "B")
graph.addEdge("A", "B")
graph.addEdge("A", "C")
graph.addEdge("C", "B")
graph.toString()

graph.remove("B")
console.log("***after remove***")
graph.toString()
